name: Calypso Live

on:
  pull_request:
    types: ['opened']

jobs:
  calypso-live:
    name: 'Links to a calypso.live instance for your branch'
    runs-on: ubuntu-latest
    # We only offer the Calypso.live link to PRs created from the Automattic organization.
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    timeout-minutes: 10
    steps:
      - name: Check if comment exists
        id: has_comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const comments = await github.rest.issues.listComments( {
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            } );
            // For debugging, if needed!
            console.log( comments );
            const existingComment = comments.data.find( comment => comment.body.includes( "calypso-live-watermark:apr@v1" ) );
            const hasComment = existingComment ? "true" : "false";
            console.log( `Has existing comment: ${ hasComment }` );
            return hasComment;
      - name: Post comment on PR
        uses: actions/github-script@v6
        if: steps.has_comment.outputs.result == 'false'
        with:
          # Skip adding a comment if we already have one.
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
                <!--calypso-live-watermark:apr@v1-->
                <details>
                  <summary>
                    Calypso Live <a href="${{steps.build_link.outputs.LINK}}">(direct link)</a>
                  </summary>
                  <table>
                    <tr>
                      <td>
                        <a href="${{steps.build_link.outputs.LINK}}">${{steps.build_link.outputs.LINK}}</a>
                      </td>
                    </tr>
                  </table>
                </details>
                <details>
                  <summary>
                    Jetpack Cloud live <a href="${{steps.build_link.outputs.LINK}}&env=jetpack">(direct link)</a>
                  </summary>
                  <table>
                    <tr>
                      <td>
                        <a href="${{steps.build_link.outputs.LINK}}&env=jetpack">${{steps.build_link.outputs.LINK}}&env=jetpack</a>
                      </td>
                    </tr>
                  </table>
                </details>
                <details>
                  <summary>
                    Automattic for Agencies live <a href="${{steps.build_link.outputs.LINK}}&env=a8c-for-agencies">(direct link)</a>
                  </summary>
                  <table>
                    <tr>
                      <td>
                        <a href="${{steps.build_link.outputs.LINK}}&env=a8c-for-agencies">${{steps.build_link.outputs.LINK}}&env=a8c-for-agencies</a>
                      </td>
                    </tr>
                  </table>
                </details>
                <details>
                  <summary>
                    Dashboard live <a href="${{steps.build_link.outputs.LINK}}&env=dashboard">(direct link)</a>
                  </summary>
                  <table>
                    <tr>
                      <td>
                        <a href="${{steps.build_link.outputs.LINK}}&env=dashboard">${{steps.build_link.outputs.LINK}}&env=dashboard</a>
                      </td>
                    </tr>
                  </table>
                </details>
              `
            })
